services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: greentrip_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
      - greentrip_network

  webserver:
    image: nginx:alpine
    container_name: greentrip_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - greentrip_network

  db:
    image: mysql:8.0
    container_name: greentrip_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: greentrip
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: greentrip
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3333:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - greentrip_network

  redis:
    image: redis:alpine
    container_name: greentrip_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - greentrip_network

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    container_name: greentrip_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - greentrip_network

networks:
  greentrip_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local